name: social_text_example
description: Example app for social_text package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  social_text:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

